#!/bin/bash
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------


# config
# ------
base=`git rev-parse --show-toplevel`
commit=`git rev-parse HEAD | cut -c-7`
tracking="$base/.git/version/marks"
cd "$base/test"
echo '__version__ = "0.0.1"' > simpletest
echo '__version__ = "0.0.1-rc98ac7a"' > rctest


# funcs
# -----
FAIL='FALSE'
assertEqual() {
	GREEN='\033[0;32m'
	RED='\033[0;31m'
	NC='\033[0m'
    if [ "$1" == "$2" ]; then
        printf $GREEN'✓'$NC
    else
        printf $RED'✗'$NC
        FAIL='TRUE'
    fi
}


# testing
# -------
# base tests
echo -n 'testing basic commands ... '
assertEqual `git v --version | wc -l` 1
assertEqual `git v -h | wc -l` 10
assertEqual `git v list | wc -l` 0
echo ''

# add test
echo -n 'testing add functionality ... '
git v add simpletest
assertEqual `git v list | wc -l` 1
git v add rctest
assertEqual `git v list | wc -l` 2
echo ''

# remove test
echo -n 'testing remove functionality ... '
git v remove rctest
assertEqual `git v list | wc -l` 1
assertEqual `git v list | grep 'simpletest' | wc -l` 1
echo ''

# # increment tests
echo -n 'testing increment functionality ... '
assertEqual `git v up patch | grep '0.0.1 --> 0.0.2' | wc -l` 1
assertEqual `git v up minor | grep '0.0.2 --> 0.1.2' | wc -l` 1
assertEqual `git v up major | grep '0.1.2 --> 1.1.2' | wc -l` 1
echo ''

# decrement tests
echo -n 'testing decrement functionality ... '
assertEqual `git v down patch | grep '1.1.2 --> 1.1.1' | wc -l` 1
assertEqual `git v down minor | grep '1.1.1 --> 1.0.1' | wc -l` 1
assertEqual `git v down major | grep '1.0.1 --> 0.0.1' | wc -l` 1
assertEqual `git v down major | grep '0.0.1 --> 0.0.1' | wc -l` 1
echo ''

# rc tests
echo -n 'testing release cycle tagging ... '
assertEqual `git v rc | grep "0.0.1 --> 0.0.1-rc$commit" | wc -l` 1
assertEqual `git v up patch | grep "0.0.1-rc$commit --> 0.0.2" | wc -l` 1
assertEqual `git v rc alpha | grep "0.0.2 --> 0.0.2-alpha" | wc -l` 1
assertEqual `git v rc beta | grep "0.0.2-alpha --> 0.0.2-beta" | wc -l` 1
git v remove simpletest
git v add rctest
assertEqual `git v rc | grep "0.0.1-rc98ac7a --> 0.0.1-rc$commit" | wc -l` 1
git v remove rctest
echo ''

# finalize
git v --reset
rm simpletest rctest
if [ $FAIL = 'TRUE' ]; then
	echo 'Fail!'
	exit 1
else
	echo 'All tests ran successfully.'
	exit 0
fi
